"""Zero-tolerance test: no Polaris references, no v9.xx / v8.xx version
references anywhere in the active code or docs.

The kindling commitment was: zero Polaris mentions, zero legacy version
references. This test is the enforcement."""
from __future__ import annotations

import pathlib
import re
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


FORBIDDEN_TEXT_PATTERNS = (
    re.compile(r"\bpolaris\b", re.IGNORECASE),
    re.compile(r"\bmycelium\b", re.IGNORECASE),
    re.compile(r"\bsanctum\b", re.IGNORECASE),
    re.compile(r"\bv[89]\.[0-9]+\b"),
    re.compile(r"\bv[89]\.[0-9]+\.[0-9]+\b"),
)

# Files that legitimately mention 'polaris' or version refs are NONE —
# we explicitly chose to expunge.
EXEMPT = {
    # Tests themselves are allowed to mention what they refuse — that
    # is, the strings appearing here. We exempt this one file.
    "tests/test_no_polaris_residue.py",
}

# Directories to skip (autogenerated, .git, etc.)
SKIP_DIRS = {".git", "__pycache__", "node_modules", ".venv", "venv"}


def _scannable_files() -> list[pathlib.Path]:
    files: list[pathlib.Path] = []
    for p in ROOT.rglob("*"):
        if not p.is_file():
            continue
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        if p.suffix not in (".py", ".sh", ".md", ".json", ".yml", ".yaml", ".toml", ".txt"):
            continue
        rel = p.relative_to(ROOT).as_posix()
        if rel in EXEMPT:
            continue
        files.append(p)
    return files


class TestNoPolarisResidue(unittest.TestCase):

    def test_no_polaris_string_anywhere(self):
        violations: list[tuple[str, int, str]] = []
        for p in _scannable_files():
            try:
                lines = p.read_text(encoding="utf-8").splitlines()
            except UnicodeDecodeError:
                continue
            for i, line in enumerate(lines, 1):
                for pat in FORBIDDEN_TEXT_PATTERNS:
                    if pat.search(line):
                        rel = p.relative_to(ROOT).as_posix()
                        violations.append((rel, i, line.strip()[:120]))
                        break
        if violations:
            msg = "Polaris / legacy-version residue found:\n" + "\n".join(
                f"  {f}:{n}: {l}" for f, n, l in violations[:25]
            )
            if len(violations) > 25:
                msg += f"\n  ... and {len(violations) - 25} more"
            self.fail(msg)


if __name__ == "__main__":
    unittest.main()
