"""Daedalus — master craftsman, builder of the Labyrinth.

In myth: Daedalus built the Labyrinth to contain the Minotaur — a
structure so intricate that even its own creator nearly could not
escape it. He also built wings of wax and feathers; his son Icarus
flew too close to the sun and fell.

In Olympus, Daedalus is the **cartographer**. The cognitive
architecture of Olympus — Hephaestus → Momus → Delphi → Styx →
Prometheus → Epimetheus → Cassandra — is itself a labyrinth: many
paths, many gates, many feedback loops. Daedalus generates Mermaid
diagrams that make this labyrinth legible. The map IS his Labyrinth
made visible.

Daedalus writes to `codex/ARCHITECTURE.md`. GitHub renders Mermaid
natively, so the diagram appears on the repo's front-facing docs.

Re-arguing the prior refusal: the missing-figures arc refused
Daedalus on AP8 for the vague role 'tool-builder / code-gen.' The
role *now* is specific and load-bearing — auto-maintained
architecture documentation that drifts only when the architecture
itself drifts. Per Delphi 2026-05-18-compass-rose-arc.md.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from olympus.primordials.gaia import root
from olympus.primordials.nyx import Nyx


@dataclass
class CartographyResult:
    """One cartography pass — what was drawn, where."""
    written_at: str
    output_path: str
    diagrams_rendered: int
    bytes_written: int


@dataclass
class _Edge:
    src: str
    dst: str
    label: str = ""


class Daedalus:
    """The cartographer. Renders the cognitive flow as Mermaid."""

    OUTPUT = "codex/ARCHITECTURE.md"

    # The cognitive-flow graph. Each tuple is (from, to, label).
    # Hand-maintained because it encodes the *load-bearing* relationships,
    # not every import. If a load-bearing edge is added or removed, this
    # edge list updates — that drift is itself a Hephaestus signal.
    _COGNITIVE_FLOW: tuple[tuple[str, str, str], ...] = (
        # ─── Observation ─────────────────────────────────────────
        ("Hydra", "Athena", "findings"),
        ("Argos", "Athena", "pheromones"),
        ("Argos", "CorrelationEngine", "pheromones"),
        # ─── Synthesis ──────────────────────────────────────────
        ("Athena", "Hephaestus", "brief"),
        ("Mnemosyne", "Athena", "history"),
        # ─── Architect / Anti-Architect ─────────────────────────
        ("Hephaestus", "Momus", "proposal"),
        ("Momus", "Hephaestus", "AP1..AP8 dings"),
        ("Hephaestus", "Delphi", "ratified proposal"),
        # ─── Decision + Oath ────────────────────────────────────
        ("Delphi", "Zeus", "decision"),
        ("Zeus", "Styx", "oath"),
        ("Styx", "Mnemosyne", "oath record"),
        # ─── Action ─────────────────────────────────────────────
        ("Zeus", "ActionQueue", "ratify / reject"),
        ("ActionQueue", "Prometheus", "LOW ratified"),
        ("ActionQueue", "Mnemosyne", "ratified / rejected"),
        # ─── Self-improvement ───────────────────────────────────
        ("Prometheus", "Mnemosyne", "before/after"),
        ("Mnemosyne", "Epimetheus", "events"),
        ("Epimetheus", "Mnemosyne", "hindsights"),
        ("Mnemosyne", "Cassandra", "ignored alerts"),
        ("Cassandra", "Mnemosyne", "vindications"),
        # ─── Live state ────────────────────────────────────────
        ("Session", "Atlas", "bear/release"),
        ("Prometheus", "Atlas", "bear/release"),
        # ─── Recovery ──────────────────────────────────────────
        ("Furies", "Mnemosyne", "invariant.violated"),
        ("Mnemosyne", "Pan", "violation rate"),
        ("Pan", "ActionQueue", "guard ratification"),
        ("Asclepius", "Iris", "rebuild"),
        ("Asclepius", "Pan", "validate state"),
        ("Asclepius", "Atlas", "flag hung burdens"),
        # ─── Archive ───────────────────────────────────────────
        ("Atlas", "Charon", "released burdens"),
        ("Charon", "Hades", "ferry"),
        # ─── Presentation ──────────────────────────────────────
        ("Mnemosyne", "Iris", "data island"),
        ("Mnemosyne", "Wisdom", "aggregate"),
        ("Daedalus", "ARCHITECTURE.md", "Mermaid"),
    )

    def _node_id(self, name: str) -> str:
        """Mermaid-safe node id (alnum only)."""
        return "".join(c for c in name if c.isalnum())

    def render_cognitive_flow(self) -> str:
        """Return the Mermaid diagram of the cognitive flow as text."""
        lines = [
            "```mermaid",
            "%% Cognitive flow — generated by Daedalus.",
            "%% Edit src/olympus/heroes/daedalus.py::_COGNITIVE_FLOW to amend.",
            "flowchart LR",
            "",
            "    %% — observation ———————————————————————",
            "    Hydra[(HYDRA)]:::watcher",
            "    Argos[(Argos swarm)]:::watcher",
            "    Furies[(Furies)]:::watcher",
            "",
            "    %% — reasoning ————————————————————————",
            "    Athena{{Athena}}:::reasoner",
            "    Hephaestus{{Hephaestus}}:::reasoner",
            "    Momus{{Momus}}:::reasoner",
            "    Epimetheus{{Epimetheus}}:::reasoner",
            "    Cassandra{{Cassandra}}:::reasoner",
            "",
            "    %% — authority ————————————————————————",
            "    Delphi[/Delphi/]:::authority",
            "    Zeus[/Zeus/]:::authority",
            "    Styx[(Styx)]:::authority",
            "",
            "    %% — execution ————————————————————————",
            "    ActionQueue[ActionQueue]:::execution",
            "    Prometheus[Prometheus]:::execution",
            "    Asclepius[Asclepius]:::execution",
            "    Pan[Pan]:::execution",
            "",
            "    %% — state ————————————————————————————",
            "    Mnemosyne[(Mnemosyne)]:::state",
            "    Atlas[(Atlas)]:::state",
            "    Charon[Charon]:::state",
            "    Hades[(Hades)]:::state",
            "",
            "    %% — presentation —————————————————————",
            "    Iris[Iris]:::view",
            "    Wisdom[Wisdom]:::view",
            "    Session[Session]:::view",
            "    CorrelationEngine[CorrelationEngine]:::view",
            "    Daedalus{{Daedalus}}:::reasoner",
            "    ARCHITECTUREmd[(ARCHITECTURE.md)]:::view",
            "",
        ]
        # Edges
        for src, dst, label in self._COGNITIVE_FLOW:
            sid = self._node_id(src)
            did = self._node_id(dst)
            if label:
                lines.append(f"    {sid} -- \"{label}\" --> {did}")
            else:
                lines.append(f"    {sid} --> {did}")
        # Classes
        lines.extend([
            "",
            "    classDef watcher    fill:#3a3a4e,stroke:#aaa,color:#fff",
            "    classDef reasoner   fill:#5e4b8b,stroke:#aaa,color:#fff",
            "    classDef authority  fill:#7e3a3a,stroke:#aaa,color:#fff",
            "    classDef execution  fill:#3a7e4f,stroke:#aaa,color:#fff",
            "    classDef state      fill:#7e6f3a,stroke:#aaa,color:#fff",
            "    classDef view       fill:#3a6f7e,stroke:#aaa,color:#fff",
            "```",
        ])
        return "\n".join(lines)

    # ─────────────────────────────────────────────────────────
    # Sacred-geometry SVG (phi arc) — Metatron's Cube + Vesica Piscis
    # ─────────────────────────────────────────────────────────

    # The 13 canonical figures for Metatron's Cube — the 12 Olympians
    # + Hestia. Order matters: index 0 is the center; 1..6 form the
    # inner hexagon (the seed-of-life ring); 7..12 form the outer
    # hexagon. Edges connect every node to every other (78 total).
    _METATRON_13: tuple[str, ...] = (
        "Zeus",        # 0 — center
        "Hera",        # 1..6 inner hexagon
        "Poseidon",
        "Demeter",
        "Athena",
        "Apollo",
        "Artemis",
        "Ares",        # 7..12 outer hexagon
        "Aphrodite",
        "Hephaestus",
        "Hermes",
        "Dionysus",
        "Hestia",
    )

    def render_metatron_cube(self, *,
                              size: int = 520,
                              radius_inner: float | None = None,
                              radius_outer: float | None = None,
                              ) -> str:
        """Render Metatron's Cube as inline SVG. 13 nodes for the 13
        canonical Olympian figures; every-vertex-to-every-vertex edges
        in a faded ink so the underlying sacred geometry shows.
        Returns the SVG element as a string (suitable for embedding
        in a markdown file)."""
        import math as _m
        cx, cy = size / 2, size / 2
        ri = radius_inner if radius_inner is not None else size * 0.18
        ro = radius_outer if radius_outer is not None else size * 0.36
        node_r = max(14, int(size * 0.035))

        # Coordinates for the 13 nodes
        coords: list[tuple[float, float]] = [(cx, cy)]
        for i in range(6):
            theta = -_m.pi / 2 + i * (2 * _m.pi / 6)
            coords.append((cx + ri * _m.cos(theta),
                            cy + ri * _m.sin(theta)))
        for i in range(6):
            # Outer hexagon offset by 30° so it interleaves with inner
            theta = -_m.pi / 2 + _m.pi / 6 + i * (2 * _m.pi / 6)
            coords.append((cx + ro * _m.cos(theta),
                            cy + ro * _m.sin(theta)))

        # Build the SVG
        lines: list[str] = [
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {size} {size}" '
            f'role="img" aria-label="Metatron\'s Cube of the 13 canonical Olympian figures" '
            f'style="background:#0f0f17">',
            '  <defs>',
            '    <style>',
            '      .edge { stroke: rgba(212,160,23,0.18); fill: none; }',
            '      .vesica { stroke: rgba(255,255,255,0.05); fill: none; }',
            '      .node-circle { stroke: #d4a017; stroke-width: 1.5; '
            'fill: #2d1a1f; }',
            '      .node-center { fill: #7e3a3a; }',
            '      .label { fill: #ecebe4; font: bold 11px '
            '"Helvetica Neue", Arial; text-anchor: middle; '
            'dominant-baseline: middle; }',
            '    </style>',
            '  </defs>',
            '  <!-- vesica-piscis ring of seed-of-life circles -->',
        ]
        for x, y in coords:
            lines.append(
                f'  <circle class="vesica" cx="{x:.2f}" cy="{y:.2f}" '
                f'r="{ri:.2f}"/>'
            )
        # Edges — every node to every other
        lines.append('  <!-- every-to-every edges -->')
        for i in range(len(coords)):
            for j in range(i + 1, len(coords)):
                xi, yi = coords[i]
                xj, yj = coords[j]
                lines.append(
                    f'  <line class="edge" '
                    f'x1="{xi:.2f}" y1="{yi:.2f}" '
                    f'x2="{xj:.2f}" y2="{yj:.2f}"/>'
                )
        # Nodes (drawn last so they sit on top of the edges)
        lines.append('  <!-- nodes -->')
        for i, (x, y) in enumerate(coords):
            cls = "node-circle node-center" if i == 0 else "node-circle"
            lines.append(
                f'  <circle class="{cls}" cx="{x:.2f}" cy="{y:.2f}" '
                f'r="{node_r}"/>'
            )
            # Label slightly below
            label = self._METATRON_13[i]
            lines.append(
                f'  <text class="label" x="{x:.2f}" '
                f'y="{y + node_r + 13:.2f}">{label}</text>'
            )
        lines.append('</svg>')
        return "\n".join(lines)

    def render_vesica_piscis(self, *,
                              left_label: str = "Athena (synthesis)",
                              right_label: str = "Hephaestus (drift)",
                              center_label: str = "proposal",
                              size: int = 420) -> str:
        """Render the Vesica Piscis — two circles intersecting; the
        labels name the two domains and the meaning of their overlap."""
        cx = size / 2
        cy = size / 2
        r = size * 0.28
        offset = r * 0.5  # gives the canonical vesica-piscis overlap
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {size} {int(size * 0.7)}" '
            f'role="img" aria-label="Vesica Piscis — {left_label} meets {right_label}" '
            f'style="background:#0f0f17">\n'
            f'  <defs>\n'
            f'    <style>\n'
            f'      .v-circle {{ stroke: #d4a017; stroke-width: 2.5; '
            f'fill: rgba(212,160,23,0.04); }}\n'
            f'      .v-label {{ fill: #ecebe4; font: bold 13px '
            f'"Helvetica Neue", Arial; text-anchor: middle; }}\n'
            f'      .v-center {{ fill: #f0c43a; font: italic 12px '
            f'"Helvetica Neue", Arial; text-anchor: middle; }}\n'
            f'    </style>\n'
            f'  </defs>\n'
            f'  <circle class="v-circle" cx="{cx - offset:.2f}" '
            f'cy="{cy:.2f}" r="{r:.2f}"/>\n'
            f'  <circle class="v-circle" cx="{cx + offset:.2f}" '
            f'cy="{cy:.2f}" r="{r:.2f}"/>\n'
            f'  <text class="v-label" x="{cx - offset - r * 0.5:.2f}" '
            f'y="{cy + r + 30:.2f}">{left_label}</text>\n'
            f'  <text class="v-label" x="{cx + offset + r * 0.5:.2f}" '
            f'y="{cy + r + 30:.2f}">{right_label}</text>\n'
            f'  <text class="v-center" x="{cx:.2f}" y="{cy:.2f}">'
            f'{center_label}</text>\n'
            f'</svg>'
        )

    def render_tier_map(self) -> str:
        """Mermaid diagram of the static tier layout."""
        from olympus.titans.coeus import coeus
        pop = coeus.ask("pantheon-population")
        lines = [
            "```mermaid",
            "%% Tier map — generated by Daedalus.",
            "flowchart TB",
            "",
            "    subgraph Cosmos",
            "        direction TB",
            "        Primordials[Primordials]",
            "        Titans[Titans]",
            "        Olympians[Olympians]",
            "        Underworld[Underworld]",
            "    end",
            "",
            "    subgraph Triads",
            "        direction TB",
            "        Fates[Fates]",
            "        Furies[Furies]",
            "        Graces[Graces]",
            "    end",
            "",
            "    subgraph Service",
            "        direction TB",
            "        Muses[Muses]",
            "        Heroes[Heroes]",
            "        Monsters[Monsters]",
            "    end",
            "",
            "    Primordials --> Titans --> Olympians",
            "    Olympians --> Underworld",
            "    Olympians --> Triads",
            "    Olympians --> Service",
            "",
        ]
        # Annotate with population
        for tier in ("primordials", "titans", "olympians", "underworld",
                     "fates", "furies", "graces", "muses", "heroes",
                     "monsters"):
            count = pop.get(tier, 0)
            pretty = tier.capitalize() if tier != "underworld" else "Underworld"
            lines.append(f"    {pretty} --- {pretty}Count(({count}))")
        lines.extend(["```"])
        return "\n".join(lines)

    def _source_hash(self) -> str:
        """SHA-256 of the load-bearing source-of-truth (_COGNITIVE_FLOW
        edge list). Embedded in the rendered document as a lineage
        receipt — Asclepius can detect drift if the document doesn't
        match the current source."""
        import hashlib
        import json as _json
        material = _json.dumps(list(self._COGNITIVE_FLOW), sort_keys=True)
        return hashlib.sha256(material.encode("utf-8")).hexdigest()

    def render_full_document(self) -> str:
        """The complete ARCHITECTURE.md document."""
        ts = Nyx.now().isoformat()
        lineage = self._source_hash()
        metatron = self.render_metatron_cube()
        vesica = self.render_vesica_piscis(
            left_label="Athena (synthesis)",
            right_label="Hephaestus (drift)",
            center_label="proposal",
        )
        return f"""<div align="center">

# ARCHITECTURE

**the labyrinth made visible**

*generated by Daedalus — {ts}*

</div>

<!-- lineage: cognitive-flow-sha256={lineage} -->

---

## The thirteen — Metatron's Cube

The twelve Olympians plus Hestia, arranged in the canonical sacred-
geometry layout. Every node connects to every other node; the inner
ring is the seed-of-life hexagon; Zeus sits at the cosmic axis.

<div align="center">

{metatron}

</div>

## Where domains meet — Vesica Piscis

The intersection of Athena's synthesis and Hephaestus's drift is
where a proposal is born. The overlap is the proposal itself.

<div align="center">

{vesica}

</div>

---

This document is regenerated by `invoke cartograph --write` and reflects
the **load-bearing relationships** between the substrate's named figures,
not every Python import. The edge list lives in
`src/olympus/heroes/daedalus.py::Daedalus._COGNITIVE_FLOW` — amending
that list changes this map.

---

## Cognitive flow

How a session moves from observation to action to reflection to archive.

{self.render_cognitive_flow()}

### Reading the diagram

- **Watchers** (slate) — observe the substrate; never modify it.
- **Reasoners** (purple) — read observations, produce briefs and proposals.
- **Authority** (red) — the operator (Zeus), the law (Delphi), the
  cryptographic continuity (Styx). The only legitimate source of HIGH-
  risk authorization.
- **Execution** (green) — turn ratified proposals into observable change.
- **State** (gold) — append-only ground truth; the audit-of-record.
- **View** (teal) — derived presentations of state. Always rebuildable
  via Asclepius.

---

## Tier map

The static structure: every named figure belongs to one of these tiers,
and the tier counts are checked by `tests/test_pantheon_coherence.py`.

{self.render_tier_map()}

---

## Drift signals

If you add a new load-bearing edge between named figures, update the
`_COGNITIVE_FLOW` edge list in `daedalus.py` and re-run
`invoke cartograph --write`. The Hephaestus drift watcher monitors this
document; if the architecture changes but the map does not, that's a
ratifiable drift signal.

---

*Per Delphi 2026-05-18-compass-rose-arc.md. The Labyrinth was Daedalus's
greatest work; the cognitive architecture map is its substrate twin.*
"""

    # ─────────────────────────────────────────────────────────
    # Graph analysis (aegis arc) — Daedalus's labyrinth becomes
    # queryable as a graph, not just renderable as a picture.
    # ─────────────────────────────────────────────────────────

    def graph(self) -> tuple[set[str], dict[str, list[str]],
                              dict[str, list[str]]]:
        """Return (nodes, out_edges, in_edges) over _COGNITIVE_FLOW."""
        nodes: set[str] = set()
        out_edges: dict[str, list[str]] = {}
        in_edges: dict[str, list[str]] = {}
        for src, dst, _label in self._COGNITIVE_FLOW:
            nodes.add(src); nodes.add(dst)
            out_edges.setdefault(src, []).append(dst)
            in_edges.setdefault(dst, []).append(src)
        return nodes, out_edges, in_edges

    def degree(self) -> dict[str, dict[str, int]]:
        """Per-node {in, out, total} degree."""
        nodes, out_e, in_e = self.graph()
        return {
            n: {
                "in": len(in_e.get(n, [])),
                "out": len(out_e.get(n, [])),
                "total": len(in_e.get(n, [])) + len(out_e.get(n, [])),
            }
            for n in sorted(nodes)
        }

    def centrality(self) -> dict[str, float]:
        """Betweenness centrality: for each node n, the fraction of
        shortest paths between every pair (s, t) that pass through n.

        Implemented via Brandes-style accumulation, but with the small
        graph (~25 nodes) we just use single-source BFS from each
        source and count. Pure Python, no numpy.
        """
        nodes, out_e, _in_e = self.graph()
        nodes_list = sorted(nodes)
        # Initialize accumulator
        accum: dict[str, float] = {n: 0.0 for n in nodes_list}

        for s in nodes_list:
            # Single-source BFS — find shortest-path counts and
            # predecessors
            predecessors: dict[str, list[str]] = {n: [] for n in nodes_list}
            sigma: dict[str, float] = {n: 0.0 for n in nodes_list}
            sigma[s] = 1.0
            distance: dict[str, int] = {n: -1 for n in nodes_list}
            distance[s] = 0
            queue: list[str] = [s]
            stack: list[str] = []
            while queue:
                v = queue.pop(0)
                stack.append(v)
                for w in out_e.get(v, []):
                    if distance[w] < 0:
                        distance[w] = distance[v] + 1
                        queue.append(w)
                    if distance[w] == distance[v] + 1:
                        sigma[w] += sigma[v]
                        predecessors[w].append(v)
            # Back-accumulate
            delta: dict[str, float] = {n: 0.0 for n in nodes_list}
            while stack:
                w = stack.pop()
                for v in predecessors[w]:
                    if sigma[w] > 0:
                        delta[v] += (sigma[v] / sigma[w]) * (1.0 + delta[w])
                if w != s:
                    accum[w] += delta[w]

        # Normalize: divide by (n-1)(n-2) for directed graphs
        n = len(nodes_list)
        if n >= 3:
            norm = (n - 1) * (n - 2)
            for k in accum:
                accum[k] /= norm
        return accum

    def load_bearing_figures(self, top: int = 10) -> list[tuple[str, float]]:
        """Top N figures by betweenness centrality."""
        c = self.centrality()
        return sorted(c.items(), key=lambda kv: kv[1], reverse=True)[:top]

    def cartograph(self, *, write: bool = False) -> CartographyResult:
        """Render the architecture document. If write=True, persists
        to codex/ARCHITECTURE.md."""
        doc = self.render_full_document()
        out_path = root.child(*self.OUTPUT.split("/"))
        if write:
            out_path.write_text(doc, encoding="utf-8")
        return CartographyResult(
            written_at=Nyx.now().isoformat(),
            output_path=out_path.as_posix() if write else "(not written)",
            diagrams_rendered=2,  # cognitive flow + tier map
            bytes_written=len(doc.encode("utf-8")) if write else 0,
        )


daedalus = Daedalus()
