"""Daedalus — master craftsman, builder of the Labyrinth.

In myth: Daedalus built the Labyrinth to contain the Minotaur — a
structure so intricate that even its own creator nearly could not
escape it. He also built wings of wax and feathers; his son Icarus
flew too close to the sun and fell.

In Olympus, Daedalus is the **cartographer**. The cognitive
architecture of Olympus — Hephaestus → Momus → Delphi → Styx →
Prometheus → Epimetheus → Cassandra — is itself a labyrinth: many
paths, many gates, many feedback loops. Daedalus generates Mermaid
diagrams that make this labyrinth legible. The map IS his Labyrinth
made visible.

Daedalus writes to `codex/ARCHITECTURE.md`. GitHub renders Mermaid
natively, so the diagram appears on the repo's front-facing docs.

Re-arguing the prior refusal: the missing-figures arc refused
Daedalus on AP8 for the vague role 'tool-builder / code-gen.' The
role *now* is specific and load-bearing — auto-maintained
architecture documentation that drifts only when the architecture
itself drifts. Per Delphi 2026-05-18-compass-rose-arc.md.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from olympus.primordials.gaia import root
from olympus.primordials.nyx import Nyx


@dataclass
class CartographyResult:
    """One cartography pass — what was drawn, where."""
    written_at: str
    output_path: str
    diagrams_rendered: int
    bytes_written: int


@dataclass
class _Edge:
    src: str
    dst: str
    label: str = ""


class Daedalus:
    """The cartographer. Renders the cognitive flow as Mermaid."""

    OUTPUT = "codex/ARCHITECTURE.md"

    # The cognitive-flow graph. Each tuple is (from, to, label).
    # Hand-maintained because it encodes the *load-bearing* relationships,
    # not every import. If a load-bearing edge is added or removed, this
    # edge list updates — that drift is itself a Hephaestus signal.
    _COGNITIVE_FLOW: tuple[tuple[str, str, str], ...] = (
        # ─── Observation ─────────────────────────────────────────
        ("Hydra", "Athena", "findings"),
        ("Argos", "Athena", "pheromones"),
        ("Argos", "CorrelationEngine", "pheromones"),
        # ─── Synthesis ──────────────────────────────────────────
        ("Athena", "Hephaestus", "brief"),
        ("Mnemosyne", "Athena", "history"),
        # ─── Architect / Anti-Architect ─────────────────────────
        ("Hephaestus", "Momus", "proposal"),
        ("Momus", "Hephaestus", "AP1..AP8 dings"),
        ("Hephaestus", "Delphi", "ratified proposal"),
        # ─── Decision + Oath ────────────────────────────────────
        ("Delphi", "Zeus", "decision"),
        ("Zeus", "Styx", "oath"),
        ("Styx", "Mnemosyne", "oath record"),
        # ─── Action ─────────────────────────────────────────────
        ("Zeus", "ActionQueue", "ratify / reject"),
        ("ActionQueue", "Prometheus", "LOW ratified"),
        ("ActionQueue", "Mnemosyne", "ratified / rejected"),
        # ─── Self-improvement ───────────────────────────────────
        ("Prometheus", "Mnemosyne", "before/after"),
        ("Mnemosyne", "Epimetheus", "events"),
        ("Epimetheus", "Mnemosyne", "hindsights"),
        ("Mnemosyne", "Cassandra", "ignored alerts"),
        ("Cassandra", "Mnemosyne", "vindications"),
        # ─── Live state ────────────────────────────────────────
        ("Session", "Atlas", "bear/release"),
        ("Prometheus", "Atlas", "bear/release"),
        # ─── Recovery ──────────────────────────────────────────
        ("Furies", "Mnemosyne", "invariant.violated"),
        ("Mnemosyne", "Pan", "violation rate"),
        ("Pan", "ActionQueue", "guard ratification"),
        ("Asclepius", "Iris", "rebuild"),
        ("Asclepius", "Pan", "validate state"),
        ("Asclepius", "Atlas", "flag hung burdens"),
        # ─── Archive ───────────────────────────────────────────
        ("Atlas", "Charon", "released burdens"),
        ("Charon", "Hades", "ferry"),
        # ─── Presentation ──────────────────────────────────────
        ("Mnemosyne", "Iris", "data island"),
        ("Mnemosyne", "Wisdom", "aggregate"),
        ("Daedalus", "ARCHITECTURE.md", "Mermaid"),
    )

    def _node_id(self, name: str) -> str:
        """Mermaid-safe node id (alnum only)."""
        return "".join(c for c in name if c.isalnum())

    def render_cognitive_flow(self) -> str:
        """Return the Mermaid diagram of the cognitive flow as text."""
        lines = [
            "```mermaid",
            "%% Cognitive flow — generated by Daedalus.",
            "%% Edit src/olympus/heroes/daedalus.py::_COGNITIVE_FLOW to amend.",
            "flowchart LR",
            "",
            "    %% — observation ———————————————————————",
            "    Hydra[(HYDRA)]:::watcher",
            "    Argos[(Argos swarm)]:::watcher",
            "    Furies[(Furies)]:::watcher",
            "",
            "    %% — reasoning ————————————————————————",
            "    Athena{{Athena}}:::reasoner",
            "    Hephaestus{{Hephaestus}}:::reasoner",
            "    Momus{{Momus}}:::reasoner",
            "    Epimetheus{{Epimetheus}}:::reasoner",
            "    Cassandra{{Cassandra}}:::reasoner",
            "",
            "    %% — authority ————————————————————————",
            "    Delphi[/Delphi/]:::authority",
            "    Zeus[/Zeus/]:::authority",
            "    Styx[(Styx)]:::authority",
            "",
            "    %% — execution ————————————————————————",
            "    ActionQueue[ActionQueue]:::execution",
            "    Prometheus[Prometheus]:::execution",
            "    Asclepius[Asclepius]:::execution",
            "    Pan[Pan]:::execution",
            "",
            "    %% — state ————————————————————————————",
            "    Mnemosyne[(Mnemosyne)]:::state",
            "    Atlas[(Atlas)]:::state",
            "    Charon[Charon]:::state",
            "    Hades[(Hades)]:::state",
            "",
            "    %% — presentation —————————————————————",
            "    Iris[Iris]:::view",
            "    Wisdom[Wisdom]:::view",
            "    Session[Session]:::view",
            "    CorrelationEngine[CorrelationEngine]:::view",
            "    Daedalus{{Daedalus}}:::reasoner",
            "    ARCHITECTUREmd[(ARCHITECTURE.md)]:::view",
            "",
        ]
        # Edges
        for src, dst, label in self._COGNITIVE_FLOW:
            sid = self._node_id(src)
            did = self._node_id(dst)
            if label:
                lines.append(f"    {sid} -- \"{label}\" --> {did}")
            else:
                lines.append(f"    {sid} --> {did}")
        # Classes
        lines.extend([
            "",
            "    classDef watcher    fill:#3a3a4e,stroke:#aaa,color:#fff",
            "    classDef reasoner   fill:#5e4b8b,stroke:#aaa,color:#fff",
            "    classDef authority  fill:#7e3a3a,stroke:#aaa,color:#fff",
            "    classDef execution  fill:#3a7e4f,stroke:#aaa,color:#fff",
            "    classDef state      fill:#7e6f3a,stroke:#aaa,color:#fff",
            "    classDef view       fill:#3a6f7e,stroke:#aaa,color:#fff",
            "```",
        ])
        return "\n".join(lines)

    def render_tier_map(self) -> str:
        """Mermaid diagram of the static tier layout."""
        from olympus.titans.coeus import coeus
        pop = coeus.ask("pantheon-population")
        lines = [
            "```mermaid",
            "%% Tier map — generated by Daedalus.",
            "flowchart TB",
            "",
            "    subgraph Cosmos",
            "        direction TB",
            "        Primordials[Primordials]",
            "        Titans[Titans]",
            "        Olympians[Olympians]",
            "        Underworld[Underworld]",
            "    end",
            "",
            "    subgraph Triads",
            "        direction TB",
            "        Fates[Fates]",
            "        Furies[Furies]",
            "        Graces[Graces]",
            "    end",
            "",
            "    subgraph Service",
            "        direction TB",
            "        Muses[Muses]",
            "        Heroes[Heroes]",
            "        Monsters[Monsters]",
            "    end",
            "",
            "    Primordials --> Titans --> Olympians",
            "    Olympians --> Underworld",
            "    Olympians --> Triads",
            "    Olympians --> Service",
            "",
        ]
        # Annotate with population
        for tier in ("primordials", "titans", "olympians", "underworld",
                     "fates", "furies", "graces", "muses", "heroes",
                     "monsters"):
            count = pop.get(tier, 0)
            pretty = tier.capitalize() if tier != "underworld" else "Underworld"
            lines.append(f"    {pretty} --- {pretty}Count(({count}))")
        lines.extend(["```"])
        return "\n".join(lines)

    def render_full_document(self) -> str:
        """The complete ARCHITECTURE.md document."""
        ts = Nyx.now().isoformat()
        return f"""<div align="center">

# ARCHITECTURE

**the labyrinth made visible**

*generated by Daedalus — {ts}*

</div>

---

This document is regenerated by `invoke cartograph --write` and reflects
the **load-bearing relationships** between the substrate's named figures,
not every Python import. The edge list lives in
`src/olympus/heroes/daedalus.py::Daedalus._COGNITIVE_FLOW` — amending
that list changes this map.

---

## Cognitive flow

How a session moves from observation to action to reflection to archive.

{self.render_cognitive_flow()}

### Reading the diagram

- **Watchers** (slate) — observe the substrate; never modify it.
- **Reasoners** (purple) — read observations, produce briefs and proposals.
- **Authority** (red) — the operator (Zeus), the law (Delphi), the
  cryptographic continuity (Styx). The only legitimate source of HIGH-
  risk authorization.
- **Execution** (green) — turn ratified proposals into observable change.
- **State** (gold) — append-only ground truth; the audit-of-record.
- **View** (teal) — derived presentations of state. Always rebuildable
  via Asclepius.

---

## Tier map

The static structure: every named figure belongs to one of these tiers,
and the tier counts are checked by `tests/test_pantheon_coherence.py`.

{self.render_tier_map()}

---

## Drift signals

If you add a new load-bearing edge between named figures, update the
`_COGNITIVE_FLOW` edge list in `daedalus.py` and re-run
`invoke cartograph --write`. The Hephaestus drift watcher monitors this
document; if the architecture changes but the map does not, that's a
ratifiable drift signal.

---

*Per Delphi 2026-05-18-compass-rose-arc.md. The Labyrinth was Daedalus's
greatest work; the cognitive architecture map is its substrate twin.*
"""

    def cartograph(self, *, write: bool = False) -> CartographyResult:
        """Render the architecture document. If write=True, persists
        to codex/ARCHITECTURE.md."""
        doc = self.render_full_document()
        out_path = root.child(*self.OUTPUT.split("/"))
        if write:
            out_path.write_text(doc, encoding="utf-8")
        return CartographyResult(
            written_at=Nyx.now().isoformat(),
            output_path=out_path.as_posix() if write else "(not written)",
            diagrams_rendered=2,  # cognitive flow + tier map
            bytes_written=len(doc.encode("utf-8")) if write else 0,
        )


daedalus = Daedalus()
